
services:
  db:
    image: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: demoitpdb
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: